version: '3'

networks:
  net_trinity:
    external: true
  net_local:
    name: local_ecommerce
    driver: bridge


services:
  be-trinity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-trinity
    env_file:
      - .env
    restart: unless-stopped
    command:  go run main.go
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    depends_on:
      - postgres-trinity
    networks:
      - net_local
      - net_trinity

  postgres-trinity:
    image: postgres:16
    container_name: db-postgres-trinity
    restart: unless-stopped
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - net_local
      - net_trinity
