package main

import (
	"log"
	"trinity_app/controllers"
	"trinity_app/repository"
	"trinity_app/router"
	"trinity_app/services"
	"trinity_app/utils"

	_ "trinity_app/docs"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	// docs is generated by Swag CLI, you have to import it.
)

//	@title			Documenting API
//	@version		3.0
//	@description	API Document
//	@termsOfService

//	@externalDocs.description	OpenAPI
//	@externalDocs.url			https://swagger.io/resources/open-api/

func main() {
	config := utils.Viper

	dsn := config.GetString("POSTGRES_DB_URL")
	gormDB, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})

	if err != nil {
		log.Fatal(err)
	}

	repo := repository.NewRepo(gormDB)
	services := services.NewServices(repo)
	controllers := controllers.NewControllers(services)

	router := router.NewRouter(controllers)
	err = router.Start(config.GetString("SERVER_ADD"))

	if err != nil {
		log.Fatal("[Cannot start server]: " + err.Error())
	}
}
